"""add index on event_winners.event_id

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-26 10:57:04.017864

"""
from collections.abc import Sequence

from alembic import op


revision: str = '0002'
down_revision: str | Sequence[str] | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_event_winners_event_id'), 'event_winners', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_winners_event_id'), table_name='event_winners')
    # ### end Alembic commands ###
